#' @export
theme_trm <- function(left_margin, right_margin, text_size){
  ggplot2::theme(plot.margin = ggplot2::margin(t = 30),
                 axis.ticks = ggplot2::element_blank(),
                 axis.text = ggplot2::element_text(size = text_size, family = "Georgia"),
                 legend.position="bottom",
                 legend.margin = margin(b = 0.5, unit = "cm"),
                 legend.key.height = grid::unit(0.4, 'cm'),
                 legend.spacing.y = grid::unit(0.4, 'cm'),
                 legend.background = ggplot2::element_rect(fill = "#ECECEC" ),
                 legend.text = ggplot2::element_text( size = text_size,
                                                      margin = ggplot2::margin(r = 30, unit = "pt")),
                 plot.background = ggplot2::element_rect(fill = "#ECECEC"),
                 panel.grid.major.x = ggplot2::element_blank(),
                 panel.grid.minor = ggplot2::element_blank(),
                 panel.grid.major = ggplot2::element_line(color = "#A0A0A0",
                                                          size = 0.1),
                 axis.title.y.left = ggplot2::element_text( vjust = 1.05, angle =0,
                                                            margin = ggplot2::margin(r = left_margin,
                                                                                     t = 0, b = 0, l = 10),
                                                            size = text_size),
                 axis.title.y.right = ggplot2::element_text( vjust = 1.05, angle =0,
                                                             margin = ggplot2::margin(r = 10,
                                                                                      t = 5, b = 0, l = right_margin),
                                                             size = text_size))}
